"""add components_inventory to manual_metadata

Revision ID: 26ed0774b149
Revises: 
Create Date: 2026-08-16 11:09:24.131942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26ed0774b149'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manual_metadata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('components_inventory', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manual_metadata', schema=None) as batch_op:
        batch_op.drop_column('components_inventory')

    # ### end Alembic commands ###
