"""agregar tabla manual_metadata

Revision ID: c2cf896c2a39
Revises: b1c6fcdd6ad6
Create Date: 2026-07-28 12:48:35.239867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2cf896c2a39'
down_revision = 'b1c6fcdd6ad6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manual_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manual_id', sa.Integer(), nullable=False),
    sa.Column('tools_required', sa.JSON(), nullable=True),
    sa.Column('parts_list', sa.JSON(), nullable=True),
    sa.Column('hardware_list', sa.JSON(), nullable=True),
    sa.Column('total_steps', sa.Integer(), nullable=True),
    sa.Column('safety_warnings', sa.JSON(), nullable=True),
    sa.Column('estimated_time', sa.String(length=100), nullable=True),
    sa.Column('difficulty', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['manual_id'], ['manual.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('manual_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('manual_metadata')
    # ### end Alembic commands ###
